### ISSUE TITLE
Creating a notebook doesn't immediately show

### ISSUE THREAD

**Issue by wonea** [ekblom/noterium#26]
I opened Noterium anew and created a notebook called Development. Clicked okay, waited for the NoteBook to appear in the left panel but did not. Restarted the Noterium and it now shows.

Note: Thanks for the nifty application. Been after something like this for a while!

**Comment by ekblom** [comment]
Hi @wonea, will have a look at this as soon as possible, hopefully sometime this august, not a lot of free time nowadays.

You're quite welcome, really hope it come in handy for you. Don't hesitate to ask for improvements or do a pull request. :)
